/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface JmWeatherWidgetContainer {
        "apiKey": string;
        "defaultCity": string;
        "defaultState": string;
        "drawerOpen": boolean;
    }
    interface JmWeatherWidgetLoadingSpinner {
    }
    interface JmWeatherWidgetMenuOverlay {
        "menuOpen": boolean;
        "open": () => Promise<void>;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLJmWeatherWidgetContainerElement extends Components.JmWeatherWidgetContainer, HTMLStencilElement {
    }
    var HTMLJmWeatherWidgetContainerElement: {
        prototype: HTMLJmWeatherWidgetContainerElement;
        new (): HTMLJmWeatherWidgetContainerElement;
    };
    interface HTMLJmWeatherWidgetLoadingSpinnerElement extends Components.JmWeatherWidgetLoadingSpinner, HTMLStencilElement {
    }
    var HTMLJmWeatherWidgetLoadingSpinnerElement: {
        prototype: HTMLJmWeatherWidgetLoadingSpinnerElement;
        new (): HTMLJmWeatherWidgetLoadingSpinnerElement;
    };
    interface HTMLJmWeatherWidgetMenuOverlayElement extends Components.JmWeatherWidgetMenuOverlay, HTMLStencilElement {
    }
    var HTMLJmWeatherWidgetMenuOverlayElement: {
        prototype: HTMLJmWeatherWidgetMenuOverlayElement;
        new (): HTMLJmWeatherWidgetMenuOverlayElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "jm-weather-widget-container": HTMLJmWeatherWidgetContainerElement;
        "jm-weather-widget-loading-spinner": HTMLJmWeatherWidgetLoadingSpinnerElement;
        "jm-weather-widget-menu-overlay": HTMLJmWeatherWidgetMenuOverlayElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface JmWeatherWidgetContainer {
        "apiKey"?: string;
        "defaultCity"?: string;
        "defaultState"?: string;
        "drawerOpen"?: boolean;
    }
    interface JmWeatherWidgetLoadingSpinner {
    }
    interface JmWeatherWidgetMenuOverlay {
        "menuOpen"?: boolean;
        "onJmFetchWeather"?: (event: CustomEvent<string[]>) => void;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "jm-weather-widget-container": JmWeatherWidgetContainer;
        "jm-weather-widget-loading-spinner": JmWeatherWidgetLoadingSpinner;
        "jm-weather-widget-menu-overlay": JmWeatherWidgetMenuOverlay;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "jm-weather-widget-container": LocalJSX.JmWeatherWidgetContainer & JSXBase.HTMLAttributes<HTMLJmWeatherWidgetContainerElement>;
            "jm-weather-widget-loading-spinner": LocalJSX.JmWeatherWidgetLoadingSpinner & JSXBase.HTMLAttributes<HTMLJmWeatherWidgetLoadingSpinnerElement>;
            "jm-weather-widget-menu-overlay": LocalJSX.JmWeatherWidgetMenuOverlay & JSXBase.HTMLAttributes<HTMLJmWeatherWidgetMenuOverlayElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
